### ISSUE TITLE
topsy is confused when there are nested class definitions in c++

### ISSUE THREAD

**Issue by Inc0n** [alphapapa/topsy.el#15]
when there are nested class definitions such as
```
class a 
{
    ....
    class b 
    {
    ....
    }
    ....
}
```
and the screen is showing the lines of codes after `class b`, topsy will display `class b` instead of `class a`

**Comment by alphapapa** [comment]
Topsy does not implement language-specific features.  As the readme says:

> There is currently only one function in topsy-mode-functions, one which returns the line that beginning-of-defun goes to. It should be useful in many major modes, but suggestions for additional, mode-specific functions are welcome.

**Comment by Inc0n** [comment]
Ah I see, apologize for missing that ...

**Comment by alphapapa** [comment]
No problem.  If you can recommend an improvement for C++, please do.
